### ISSUE TITLE
Dynamische Anpassung an buttonUrl

### ISSUE THREAD

**Issue by ZiZiWang** [Data-City/WindowsPaket#13]
wenn man im Windows Paket eine CSV importiere und dann nach dem erfolgreichen Import auf "Zum Datensatz" klicke wird die URL Adresse hostadresse/#/views/<collectionname> aufgerufen. Aber bei der lokalen Version sollte URL Adresse hostadresse/datacity/#/views/<collectionname> aufgerufen werden. Deswegen wirde die Seite nicht erfolgreich geöffnet. Wenn man die Seite zurück auf Homepage wechselt und die Datensätze auswählt, klappt es.
Man muss an buttonUrl https://github.com/Data-City/client/blob/master/app/scripts/controllers/import.js Zeil.49 dynamisch anpassen

**Comment by JuliaH1** [comment]
Bei mir passiert etwas anderes... Wenn ich auf "Zum Datensatz" nach dem Importieren klicke, fragt er mich folgendes: 
![local1](https://cloud.githubusercontent.com/assets/15839253/13950067/189b9f06-f029-11e5-8c80-7d249d891214.png)

Und wenn ich dann zb auf Öffnen mit Firefox gehe, zeigt er mir ein JSON Objekt:
![local2](https://cloud.githubusercontent.com/assets/15839253/13950074/27b4aec4-f029-11e5-894a-a70950348502.png)

 Wenn man aber auf DataCity klickt, und über die Datensatzübersicht auf den Datensatz klickt, geht es

**Comment by Nullmann** [comment]
Das ist genau das gleiche Verhalten, welches auch Zi beschrieben hat. Es wird die falsche Adresse aufgerufen.
Weiterführung in Issue #20
