### ISSUE TITLE
Das Bild verbindungen.00c38636.png wird nicht angezeigt

### ISSUE THREAD

**Issue by ZiZiWang** [Data-City/WindowsPaket#14]
Das Problem liegt ähnlich wie #13 beim Aufruf der URL Adresse. Es fehlt den /datacity Teil.

**Comment by Nullmann** [comment]
Das Interessante: Die beiden Bilder in der Navigationsleiste werden richtig dargestellt, obwohl sie auf die gleiche Art und Weise eingebunden werden.

**Comment by Nullmann** [comment]
Wird in Issue #20 weiter geführt
