### ISSUE TITLE
Fehlerhafte Darstellung des Datensatzes "BeispielTest"

### ISSUE THREAD

**Issue by MarcelMP** [Data-City/WindowsPaket#15]
![bug](https://cloud.githubusercontent.com/assets/15869627/13924224/c85e789c-ef83-11e5-822e-ba6aadebb3ff.PNG)

**Comment by MarcelMP** [comment]
Der Fehler tritt lediglich bei diesem Datensatz auf.

**Comment by Nullmann** [comment]
Generelles: Das gehört hier nicht rein. Das ist ein Issue, der in den Client gehören müsste. Außerdem ist der Titel nichts aussagend. Sowas wie "[Optik] Text ragt bei Ansichten über Panel hinaus" ist viel besser.

Zu dem Problem selbst:
Ich habe zwei Datensätze hochgeladen. Das Problem hier sind die Punkte innerhalb des Strings. Dadurch kann Bootstrap den String nicht ordentlich abschneiden und in eine neue Zeile packen. Hier der Vergleich:
![langer name](https://cloud.githubusercontent.com/assets/15816473/13926325/18a4a382-ef8c-11e5-8529-a8aee64440a2.png)
![langer name mit punkten](https://cloud.githubusercontent.com/assets/15816473/13926328/1a416072-ef8c-11e5-953e-81f6b42ce058.png)

Das ist nur ein kleiner Anzeigefehler, der die Integrität des Programmes nicht zerstört. Außerdem ist das eine Verhaltensweise von Bootstrap ist und an der können wir daran nichts ändern, weswegen ich den Issue schließe.
