### ISSUE TITLE
.Net Installation analog anbieten

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/WindowsPaket#16]
Das .NET greift bei der Installation auf Daten im Netz zu, die von deren Proxy geblockt werden.

Daher zwei Fragen: a) kann man eine vollständige offline Installation bereitstellen und b) für welche Programmteile wird es benötigt?

**Comment by ZiZiWang** [comment]
Von meiner Seite brauche ich vorher keine .Net Datei zu installieren, ich kann direkt durch bat file direkt die Seite aufrufen.

Von meinem iPhone gesendet

**Comment by ManuelMueller1988** [comment]
Die Stadt ließ sich über die .bat auch ohne Installation erfolgreich aufrufen/anzeigen.

Ein über den Client importierter Datensatz wurde angezeigt, jedoch nicht weiter verarbeitet werden.

@Marcus.Deem@ruv.de hat evtl noch detailliertere Aussagen

**Comment by Nullmann** [comment]
Der offizielle Installer für eine Offline-Installation vom .net Framework:
https://www.microsoft.com/de-de/download/confirmation.aspx?id=42642

**Comment by ManuelMueller1988** [comment]
Dann den bitte einbauen und Issue schließen.

**Comment by Nullmann** [comment]
Er wurde mit commit c7ba4ac1953bc5a1833643774d883954a33eb264 in den Ordner "externe Installationsdateien" hochgeladen. Issue wird geschlossen.
