### ISSUE TITLE
RESTHeart Fehlermeldung XNIO-1 task-3

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/WindowsPaket#17]
Folgende Fehlermeldung erschien nach Import und anschließendem Aufruf eines Datensatzes. Hängt es mit #16  zusammen?
![image001](https://cloud.githubusercontent.com/assets/15968962/13927710/14be77c8-ef93-11e5-8b5f-91f5f4874575.png)

**Comment by Nullmann** [comment]
Wenn die Fehlermeldung nicht mehr kommt, bitte schließen
