### ISSUE TITLE
Link aktuelle Ansicht funktioniert nicht

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/WindowsPaket#18]
Es wird keine Stadt dargestellt im Firefox (IE noch nicht getestet) (beim Client geht es)

![aktuelleansicht](https://cloud.githubusercontent.com/assets/15839253/13952293/ed59c838-f035-11e5-9be7-ff7ac42f4d85.png)

**Comment by Nullmann** [comment]
Collection? Ansicht? Was sagt die Konsole?
Bitte immer dazu schreiben...

**Comment by JuliaH1** [comment]
Das steht doch da oben...
Collection: BeispielTest
nochmal ausführlich: Klassen wurden gefiltert auf 1-86
keine Aggregation, keine Blockbildung, Standardeinstellung der Dimensionen

**Comment by MarcelMP** [comment]
![bug2](https://cloud.githubusercontent.com/assets/15869627/13954886/ee3deaec-f042-11e5-8f7f-a9bda4041cad.PNG)

Der Bug tritt auch im IE auf, wobei sogar nur ein schwarzes Bild zusehen ist
Habe es an verschiedenen Datensätzen und verschiedenen Ansichtseinstellungen probiert. Immer mit dem gleichen Bug.

**Comment by Nullmann** [comment]
Konsolenausgabe bitte?

**Comment by Nullmann** [comment]
Der Fehler wurde in der neuen Dist behoben.
