### ISSUE TITLE
Legende sieht komisch aus

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/WindowsPaket#19]
![legende](https://cloud.githubusercontent.com/assets/15839253/13952581/70dc166a-f037-11e5-922d-cf255699514a.png)

Ich schätze mal, dass es mit der nächsten dist behoben ist, da es auf dem Server normal und schön aussieht. Vorerst wollte ich es aber als Issue aufnehmen, falls es doch nicht behoben wird

**Comment by Nullmann** [comment]
Hast du das mit dem IE getestet? Die Darstellung sieht mir sehr stark nach Firefox aus, welche nach der Veränderung schon seit Längerem etwas anders aussieht.
Daran haben wir auch in der neuen Dist nichts geändert, daran sollte es also nicht liegen.

**Comment by JuliaH1** [comment]
Ja, Firefox

**Comment by MarcelMP** [comment]
Im IE sind die Drop-Down-Menü Darstellungen alle richtig
