### ISSUE TITLE
[Optik]: Vorgärten flackern und verschwinden komplett beim Heranzoomen

### ISSUE THREAD

**Issue by MarcelMP** [Data-City/WindowsPaket#21]
![bugii](https://cloud.githubusercontent.com/assets/15869627/13953346/cf01b7d2-f03b-11e5-8ce5-a7aacd1b0c14.PNG)

Der Fehler tritt bei dem vorimporiteren Datensatz "SG57mitVerbindungen" auf.
Aktiviert man die Vorgärten, flackern diese in der Stadtansicht. 
Als Dimensionen wurden gewählt: Fläche: PGMDEPTH, Höhe: MCCABE, Farbe: TOTALVERB.
Sonst wurde nicht aggreggiert, reduziert oder Blöcke definiert
Könnte der Fehler daher kommen, dass die Stadt an sich wieder sehr groß ist und dadurch die unteren Ebene  wieder sehr nah aufeinander liegen?
Dieser Fehler tritt nur im Windows Paket auf. Mit den gleichen Einstellungen im Web-Client werden die Vorgärten fehlerfrei angezeigt.

**Comment by Nullmann** [comment]
Kann ich bestätigen. Man kann sie auch nicht anklicken. Wüsste aber gerade nicht, woran das liegt. Könnte sein, dass der bereits importierte Datensatz dran Schuld ist.

**Comment by thuylinhluu** [comment]
Könnte es vielleicht daran liegen, dass bein Windows Paket eine alte Version vom Projekt drin ist?

**Comment by MarcelMP** [comment]
Fehler tritt nicht mehr auf. Vorgärten werden jetzt ohne Flackern dargestellt.
