### ISSUE TITLE
Import.bat Verbindungs.CSV wird nicht mit importiert, Connect.then is not a function

### ISSUE THREAD

**Issue by MarcelMP** [Data-City/WindowsPaket#22]
![bug](https://cloud.githubusercontent.com/assets/15869627/13954067/7b27c36e-f03f-11e5-8b80-cd61795f7386.PNG)

Über die Import.bat wurde der Datensatz "SG57_Programme.csv" importiert, zusätzlich wurde "SG57_Programmaufrufe.csv" als Verbindungs.csv importiert.

**Comment by Nullmann** [comment]
Der Fehler wird mir auch angezeigt, allerdings klappt der Import trotzdem. 
Steffens Kommentar: Der Befehl sollte "connect().then..." lauten

![issue 22](https://cloud.githubusercontent.com/assets/15816473/13955610/994df3a8-f045-11e5-9a0d-3dc44635d2d8.png)

**Comment by MarcelMP** [comment]
![bugie](https://cloud.githubusercontent.com/assets/15869627/13956260/4cebb948-f048-11e5-9c43-2d1f43aace2f.PNG)

Habe den Bug weiterhin im IE.

**Comment by spegenau** [comment]
@ZiZiWang 
Ruft deine Batch-Datei auch die Meta-Data-Generierung auf? Da muss Verbindungen true gesetzt sein, damit das Frontend weiß, dass es Verbindungsdaten gibt. 

Hat der hinweiß connect().then... statt connect.then... geholfen?

**Comment by Nullmann** [comment]
Bei mir funktioniert es wie gesagt auch so. Wenn ich connect().then ins admin-tool schreibe, kommt eine andere Fehlermeldung:

![screenshot 2016-03-22 16 16 18](https://cloud.githubusercontent.com/assets/15816473/13956558/8e4b9e3e-f049-11e5-93d4-ca6cf3fc3baf.png)

(Da wollte ich auf den Online-Server laden, nicht lokal)

**Comment by MarcelMP** [comment]
In der Gruntfile.js Zeile 172 anstatt connect. wurde connect(). eingefügt, Fehler wurde damit behoben.
