### ISSUE TITLE
Verbesserungsvorschlag: Nutzung einer Gruntfile

### ISSUE THREAD

**Issue by spegenau** [Data-City/WindowsPaket#4]
Über eine Gruntfile kann viel besser mit der MongoDB kommuniziert werden, als das mit einem Windows-Skript möglich ist.

Dadurch könnte beispielsweise die Initialisierung vereinfacht werden.

**Comment by ZiZiWang** [comment]
Ich hab die initDB Funktion in der grunt.js gelegt. Aber db.createCollection("name") funktioniert nicht. Der Fehler zeigt, dass name nicht definiert wurde. Wahrscheinlich die Form von db.createCollection() wird nicht in js unterstürtzt

**Comment by ZiZiWang** [comment]
Es wurde durch grunt Task realisiert
