### ISSUE TITLE
Systemvariablen automatisch

### ISSUE THREAD

**Issue by Nullmann** [Data-City/WindowsPaket#8]
Kann man die benötigten Systemvariablen automatisch setzen lassen?

**Comment by ZiZiWang** [comment]
Es wird nicht automatisch gesetz, weil wir nicht wissen, wo man z.B. Java installiert hat. Normalerweise, wenn man node.js, npm, grunt installiert hat, wird es in der Umgebungsvariable automatisch gesetzt und wenn man Java installiert hat, will man selbst die Systemvariable einstellen, sonst kann man es nicht benutzten. Meiner Meinung nach sollte man selbst die Systemvariablen manuell einstellen.
