### ISSUE TITLE
Import-Batch-Datei

### ISSUE THREAD

**Issue by Nullmann** [Data-City/WindowsPaket#9]
Sollte in dem Root Ordner liegen.

Sollte mehrere Abfragen machen wie
- Wo liegt die Datei (absolut, relativ) -- Hinweis, dass sie bei relativ im Ordner "admin-tools" liegen sollte
- Wie heißt sie
- Wie soll sie heißen
- Gibt es eine Verbindungsdatei?
- Ort und Name der Verbindungsdatei

Damit wird dann der Grunt-Import ausgeführt

**Comment by ZiZiWang** [comment]
Es wird in version1.1.2 hinzufügt
